[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RengaLUAGuide"
authors = [{name = "Eugene Kiryan", email = none}]
dynamic = ["version", "description"]
